---
- name: Patch solaris nodes   
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no

  tasks:
    - name: Exit is user is not root
      shell: whoami
      register: status

    - name: fail if not root
      fail:
        msg: user is not root exiting the playbook
      when: status.stdout != root

  roles:
    - solaris
